export const UI_AR = {
  'Electrical Studio':'الاستوديو الكهربائي','MAIN':'الرئيسية','Dashboard':'لوحة التحكم','Component Library':'مكتبة المكوّنات','Circuit Simulator':'محاكي الدوائر','TOOLS':'الأدوات','Electrical Calculator':'الحاسبة الكهربائية','Exercises':'التمارين','Learning Center':'مركز التعلّم','Guide':'الدليل','SUPPORT':'الدعم','Documentation':'التوثيق','About simulator':'حول المحاكي','Engineering Lab':'مختبر الهندسة','Local workspace':'مساحة عمل محلية','Engineering workspace':'مساحة عمل هندسية',
  'Search components, circuits and tools...':'ابحث عن المكوّنات والدوائر والأدوات...','Search the platform...':'ابحث في المنصة...','Search component...':'ابحث عن مكوّن...','Search parts...':'ابحث عن جزء...','Electrical Engineering Lab':'مختبر الهندسة الكهربائية','Build, test and learn electrical circuits in one workspace.':'صمّم واختبر وتعلّم الدوائر الكهربائية في مساحة عمل واحدة.','Open simulator':'فتح المحاكي','INTERACTIVE CIRCUIT LAB':'مختبر دوائر تفاعلي','Design. Connect. Test.':'صمّم. وصّل. اختبر.','Understand electricity safely.':'افهم الكهرباء بأمان.','A professional browser-based training environment for electrical, electronics and industrial automation practice.':'بيئة تدريب احترافية داخل المتصفح للكهرباء والإلكترونيات والأتمتة الصناعية.','Start new circuit':'بدء دائرة جديدة','Browse':'تصفّح','parts':'جزء','Electrical components':'مكوّنات كهربائية','Component categories':'فئات المكوّنات','Unlimited':'غير محدود','Circuit workspaces':'مساحات عمل الدوائر','Safe':'آمن','Virtual testing':'اختبار افتراضي','Starter circuits':'دوائر جاهزة','Load a complete example and start experimenting.':'حمّل مثالاً كاملاً وابدأ التجربة.','View all components →':'عرض جميع المكوّنات ←','components':'مكوّنات','Educational simulator':'محاكي تعليمي','Use this environment for learning, planning and virtual testing. Always follow qualified electrical safety practices on real installations.':'استخدم هذه البيئة للتعلّم والتخطيط والاختبار الافتراضي. التزم دائماً بقواعد السلامة الكهربائية في التركيبات الحقيقية.','COMPONENT LIBRARY':'مكتبة المكوّنات','Practice with':'تدرّب باستخدام','real electrical components':'مكوّنات كهربائية حقيقية','Search, inspect and place devices into the simulator.':'ابحث وافحص وضع الأجهزة داخل المحاكي.','categories':'فئات','All':'الكل','All difficulty levels':'كل مستويات الصعوبة','Available':'متاح','Interactive':'تفاعلي','Default':'الافتراضي','Add to simulator':'إضافة إلى المحاكي',
  'Universal Electrical Workbench':'منضدة كهربائية شاملة','Electrical • Interactive • Training':'كهرباء • تفاعلي • تدريب','LIVE':'مباشر','SIMULATE':'تشغيل المحاكاة','STOP':'إيقاف','Configure':'إعداد','Grid':'الشبكة','Delete':'حذف','New sheet':'ورقة جديدة','Component Library':'مكتبة المكوّنات','WIRE':'سلك','SELECT':'تحديد','PAN':'تحريك','detected':'مكتشف','wires':'أسلاك','Simulation + protection active':'المحاكاة والحماية نشطتان','Live electrical preview':'معاينة كهربائية مباشرة','Component Inspector':'خصائص المكوّن','Live Test Bench':'لوحة القياس المباشر','Component tag / reference':'وسم / مرجع المكوّن','Displayed rating / value':'القيمة / التصنيف المعروض','Library default':'القيمة الافتراضية للمكتبة','Electrical settings':'الإعدادات الكهربائية','Rotation':'الدوران','Contact / operating state':'حالة التلامس / التشغيل','Automatic from coil':'تلقائي من الملف','Closed / ON':'مغلق / تشغيل','Open / OFF':'مفتوح / إيقاف','Inactive / OFF':'غير نشط / إيقاف','Active / ON':'نشط / تشغيل','Voltage':'الجهد','Current':'التيار','Power':'القدرة','State':'الحالة','Terminal voltages':'جهود الأطراف','Connect a wire to terminal':'وصّل سلكاً بالطرف','Start wire':'بدء سلك','Rotate':'تدوير','Values recalculate instantly when you change a setting or connect/disconnect a terminal.':'تُعاد الحسابات فوراً عند تغيير الإعداد أو توصيل/فصل طرف.','Protection and operating logic are active.':'منطق الحماية والتشغيل نشط.','Live preview is active. Press SIMULATE to enable protection trips.':'المعاينة المباشرة نشطة. اضغط تشغيل المحاكاة لتفعيل فصل الحماية.','Maximum circuit voltage':'أقصى جهد في الدائرة','Source current':'تيار المصدر','Load power':'قدرة الحمل','Diagnostics':'التشخيص','Sources':'المصادر','Loads':'الأحمال','Active loads':'الأحمال النشطة','Protection devices':'أجهزة الحماية','Meters':'أجهزة القياس','Short circuit detected. Disconnect the source or open a protection device.':'تم اكتشاف قصر كهربائي. افصل المصدر أو افتح جهاز حماية.','The analyser updates immediately as you add parts, edit ratings and connect wires.':'يتم تحديث التحليل فوراً عند إضافة المكوّنات أو تعديل القيم أو توصيل الأسلاك.','Build your first circuit':'ابنِ دائرتك الأولى','Drag components from the library, then click connection points to wire them.':'اسحب المكوّنات من المكتبة ثم انقر نقاط التوصيل لربطها.','Select a component first':'حدد مكوّناً أولاً','Project saved in this browser':'تم حفظ المشروع في هذا المتصفح','Select a terminal on another component':'اختر طرفاً على مكوّن آخر','created':'تم إنشاؤها','ready to configure':'جاهز للإعداد','Drag to canvas or double-click to add':'اسحب إلى اللوحة أو انقر نقراً مزدوجاً للإضافة',
  'Calculator':'الحاسبة','Ohm’s law calculator':'حاسبة قانون أوم','Voltage (V)':'الجهد (V)','Resistance (Ω)':'المقاومة (Ω)','Current (A)':'التيار (A)','Power (W)':'القدرة (W)','Calculate':'احسب','Reset':'إعادة تعيين','Result':'النتيجة','Enter voltage and resistance to calculate current and power.':'أدخل الجهد والمقاومة لحساب التيار والقدرة.','Quick electrical calculations':'حسابات كهربائية سريعة',
  'Interactive exercises':'تمارين تفاعلية','Practice with guided circuit tasks.':'تدرّب على مهام دوائر موجهة.','Load exercise':'تحميل التمرين','Show answer':'إظهار الإجابة','Hide answer':'إخفاء الإجابة','Learning Center':'مركز التعلّم','Learn the simulator step by step.':'تعلّم استخدام المحاكي خطوة بخطوة.','Open guide':'فتح الدليل','Open documentation':'فتح التوثيق','Browse components':'تصفّح المكوّنات','Simulator Guide':'دليل المحاكي','Follow these steps to build and test a circuit.':'اتبع هذه الخطوات لبناء دائرة واختبارها.','Documentation':'التوثيق','Reference for the simulator controls and electrical workspace.':'مرجع لعناصر التحكم ومساحة العمل الكهربائية.','About ElectroLab':'حول ElectroLab','ElectroLab is a browser-based educational electrical simulation workspace.':'ElectroLab مساحة عمل تعليمية لمحاكاة الكهرباء داخل المتصفح.','Settings':'الإعدادات','Language':'اللغة','English':'الإنجليزية','Arabic':'العربية','Interface language':'لغة الواجهة','Project preferences':'تفضيلات المشروع','Default grid':'الشبكة الافتراضية','Enabled':'مفعلة','Disabled':'معطلة','Notifications':'الإشعارات','No new notifications. Your local simulator is ready.':'لا توجد إشعارات جديدة. المحاكي المحلي جاهز.','Search':'بحث','Go':'انتقال','Step':'الخطوة','Previous':'السابق','Next':'التالي','Left-click':'النقر بالزر الأيسر','Left-click a component to select it and edit it in the right panel.':'انقر بالزر الأيسر على أي مكوّن لتحديده وتعديله من اللوحة اليمنى.','Add a source and a load':'أضف مصدراً وحملاً','Connect the terminals':'وصّل الأطراف','Configure the component':'اضبط المكوّن','Run the simulation':'شغّل المحاكاة','Read the live values':'اقرأ القيم المباشرة','Save your project':'احفظ مشروعك','Switch language':'غيّر اللغة','Use the left mouse button to select and drag components.':'استخدم زر الفأرة الأيسر لتحديد المكوّنات وسحبها.','Selected component':'المكوّن المحدد'
}

export const CATEGORY_AR = {
  'Power & Sources':'الطاقة والمصادر','Protection':'الحماية','Switching & Control':'التبديل والتحكم','Motors & Drives':'المحركات ومغيرات السرعة','Loads & Lighting':'الأحمال والإنارة','Measurement':'القياس','Sensors':'الحساسات','Industrial Automation':'الأتمتة الصناعية','Transformers & Conversion':'المحولات والتحويل','Electronics':'الإلكترونيات','Residential':'المنزلي','Grounding & Wiring':'التأريض والتوصيلات'
}

export const PART_AR = {
'dc-source':'مصدر جهد مستمر','ac-source':'مصدر جهد متناوب','battery':'بطارية','three-phase':'مصدر ثلاثي الطور','generator':'مولّد','solar':'لوح شمسي','ups':'مزود طاقة غير منقطع UPS','dc-bus':'قضيب تيار مستمر',
'fuse':'مصهر','mcb':'قاطع مصغر MCB','mccb':'قاطع مصبوب MCCB','rcd':'قاطع تفاضلي RCD','rcbo':'قاطع RCBO','spd':'جهاز حماية من زيادة الجهد','thermal-relay':'مرحّل حراري للحمل الزائد','motor-protector':'قاطع حماية محرك','isolator':'قاطع عزل',
'switch-spst':'مفتاح SPST','switch-spdt':'مفتاح SPDT','push-no':'زر ضغط مفتوح عادةً NO','push-nc':'زر ضغط مغلق عادةً NC','emergency-stop':'إيقاف طوارئ','selector':'مفتاح اختيار','contactor':'كونتاكتور','control-relay':'مرحّل تحكم','timer-relay':'مرحّل زمني','latching-relay':'مرحّل تثبيت','solid-state-relay':'مرحّل حالة صلبة SSR','float-switch':'مفتاح عوّام','pressure-switch':'مفتاح ضغط','limit-switch':'مفتاح نهاية شوط',
'motor-1ph':'محرك أحادي الطور','motor-3ph':'محرك ثلاثي الطور','dc-motor':'محرك تيار مستمر','servo':'محرك سيرفو','stepper':'محرك خطوي','vfd':'مغير تردد VFD','soft-starter':'بادئ تشغيل ناعم','encoder':'مشفر دوراني',
'lamp':'مصباح','led-lamp':'مصباح LED','heater':'سخان','resistor-load':'حمل مقاومي','fan':'مروحة','buzzer':'طنّان','horn':'بوق','socket':'مقبس كهربائي','pilot-red':'مصباح بيان أحمر','pilot-green':'مصباح بيان أخضر',
'voltmeter':'فولتميتر','ammeter':'أميتر','ohmmeter':'أوميتر','multimeter':'ملتيميتر رقمي','clamp-meter':'ملقط قياس','wattmeter':'واط متر','energy-meter':'عداد طاقة','frequency-meter':'مقياس تردد','oscilloscope':'راسم إشارة','power-factor':'مقياس معامل القدرة',
'proximity-ind':'حساس تقاربي حثي','proximity-cap':'حساس سعوي','photoelectric':'حساس ضوئي','ultrasonic':'حساس فوق صوتي','temperature':'حساس حرارة','thermocouple':'ترموكبل','level-sensor':'حساس مستوى','pressure-transmitter':'مرسل ضغط','flow-sensor':'حساس تدفق','ldr':'حساس ضوء LDR','reed':'مفتاح Reed','hall':'حساس تأثير هول',
'plc':'PLC','plc-di':'دخل رقمي PLC','plc-do':'خرج رقمي PLC','plc-ai':'دخل تماثلي PLC','plc-ao':'خرج تماثلي PLC','hmi':'لوحة HMI','remote-io':'وحدة I/O بعيدة','safety-relay':'مرحّل أمان','pid':'متحكم PID','counter':'عداد رقمي','modbus':'بوابة Modbus','ethernet-switch':'مبدّل إيثرنت صناعي',
'transformer-1ph':'محول أحادي الطور','transformer-3ph':'محول ثلاثي الطور','ct':'محول تيار CT','pt':'محول جهد PT','bridge':'مقوم جسر','dc-supply':'مزود طاقة AC/DC','dc-dc':'محول DC/DC','inverter':'عاكس DC/AC',
'resistor':'مقاومة','potentiometer':'مقاومة متغيرة','capacitor':'مكثف','inductor':'محث','diode':'ديود','zener':'ديود زينر','led':'LED','npn':'ترانزستور NPN','pnp':'ترانزستور PNP','mosfet-n':'MOSFET قناة N','mosfet-p':'MOSFET قناة P','scr':'ثايرستور SCR','triac':'ترياك TRIAC','opamp':'مضخم عمليات','logic-and':'بوابة AND','logic-or':'بوابة OR','logic-not':'بوابة NOT',
'wall-switch':'مفتاح حائط','two-way':'مفتاح تبادلي','dimmer':'مخفت إضاءة','doorbell':'جرس باب','smoke-detector':'كاشف دخان','motion-sensor':'حساس حركة PIR','thermostat':'ثرموستات','contactor-home':'كونتاكتور معياري',
'terminal':'كتلة أطراف','earth':'أرضي حماية PE','neutral':'محايد N','phase':'طور L','busbar':'قضيب توزيع','junction':'نقطة توصيل','cable-2':'كابل ثنائي النواة','cable-3':'كابل ثلاثي النواة','cable-5':'كابل خماسي النواة',
'relay-contact-no':'تلامس مرحّل NO','relay-contact-nc':'تلامس مرحّل NC','timed-contact-no':'تلامس زمني NO','timed-contact-nc':'تلامس زمني NC','momentary-no':'زر لحظي NO','momentary-nc':'زر لحظي NC','knife-switch':'مفتاح سكين','line-switch':'مفتاح خط','flow-switch':'مفتاح تدفق','level-switch-no':'مفتاح مستوى NO','level-switch-nc':'مفتاح مستوى NC','pressure-vac-switch-no':'مفتاح ضغط/تفريغ NO','pressure-vac-switch-nc':'مفتاح ضغط/تفريغ NC','temperature-switch':'مفتاح حرارة','torque-switch':'مفتاح عزم',
'three-phase-delta':'مصدر ثلاثي الطور دلتا','three-phase-open-delta':'مصدر دلتا مفتوحة','three-phase-wye':'مصدر نجمة ثلاثي الطور','three-phase-wye-grounded':'مصدر نجمة مؤرض','polarity-positive':'علامة قطبية موجبة','polarity-negative':'علامة قطبية سالبة','chassis-ground':'أرضي هيكل','short-link':'وصلة قصر','autotransformer':'محول ذاتي','transformer-3w':'محول ثلاثي الملفات','bushing-ct':'محول تيار حلقي','hv-fuse-cutout':'مصهر فصل جهد عالٍ','lightning-arrester-gap':'مانع صواعق فجوي','lightning-arrester-mov':'مانع صواعق MOV','circuit-breaker':'قاطع دائرة عام','power-breaker':'قاطع قدرة','cb-3pole-magnetic':'قاطع مغناطيسي ثلاثي الأقطاب','drawout-breaker':'قاطع قابل للسحب','bell':'جرس كهربائي','annunciator':'لوحة إنذار','indicating-light':'مصباح بيان','machine-general':'آلة / مولد / محرك','field-compound':'ملف مجال مركب','field-series':'ملف مجال توالي','field-shunt':'ملف مجال توازي','field-pm':'مجال مغناطيس دائم',
'bench-dc-supply':'مزود تيار مستمر مختبري قابل للضبط','dual-dc-supply':'مزود تيار مستمر مزدوج','usb-supply':'مزود طاقة USB','battery-24v':'بنك بطاريات 24 فولت','pv-string':'سلسلة ألواح شمسية',
'afdd':'قاطع كشف القوس الكهربائي AFDD','earth-leakage-relay':'مرحّل تسرب أرضي','undervoltage-relay':'مرحّل انخفاض الجهد','overvoltage-relay':'مرحّل زيادة الجهد','phase-sequence-relay':'مرحّل تتابع الأطوار','thermal-fuse':'مصهر حراري','surge-fuse-combo':'وحدة حماية زيادة الجهد مع مصهر',
'key-switch':'مفتاح بمفتاح أمان','foot-switch':'مفتاح قدم','rotary-selector':'مفتاح دوار ثلاثي الوضعيات','star-delta-timer':'مرحّل زمني نجمة/دلتا','impulse-relay':'مرحّل نبضي','contactor-4p':'كونتاكتور رباعي الأقطاب','solenoid-coil':'ملف سولينويد',
'induction-motor':'محرك حثي','synchronous-motor':'محرك تزامني','universal-motor':'محرك شامل','geared-motor':'محرك مع علبة تروس','pump-motor':'محرك مضخة','linear-actuator':'مشغل خطي',
'incandescent-lamp':'مصباح متوهج','fluorescent-lamp':'مصباح فلورسنت','emergency-light':'إنارة طوارئ','heating-element':'عنصر تسخين','compressor-load':'ضاغط','solenoid-valve':'صمام سولينويد',
'phase-sequence-meter':'مقياس تتابع الأطوار','insulation-tester':'جهاز اختبار العزل','megohmmeter':'ميغومتر','tachometer':'مقياس سرعة الدوران','temperature-meter':'مقياس حرارة',
'current-sensor':'حساس تيار','voltage-sensor':'حساس جهد','vibration-sensor':'حساس اهتزاز','humidity-sensor':'حساس رطوبة','magnetic-proximity':'حساس تقاربي مغناطيسي',
'plc-cpu':'وحدة معالجة PLC','signal-isolator':'عازل إشارة','signal-converter':'محول إشارة','io-link-master':'وحدة IO-Link رئيسية',
'isolation-transformer':'محول عزل','variac':'محول ذاتي متغير Variac','buck-converter':'محول خافض Buck','boost-converter':'محول رافع Boost','battery-charger':'شاحن بطارية',
'ntc':'مقاومة حرارية NTC','ptc':'مقاومة حرارية PTC','varistor':'فارستور MOV','photodiode':'فوتوديود','optocoupler':'عازل ضوئي Optocoupler',
'ceiling-fan':'مروحة سقف','exhaust-fan':'مروحة شفط','water-heater':'سخان ماء كهربائي','schuko-socket':'مقبس شوكو',
'fused-terminal':'كتلة أطراف بمصهر','disconnect-terminal':'كتلة أطراف قابلة للفصل','earth-terminal':'طرف أرضي حماية','test-point':'نقطة اختبار كهربائية'
}

export const STATE_AR = {
  'IDLE':'خامل','OFF':'متوقف','ON':'تشغيل','LIT':'مضيء','RUNNING':'يعمل','SPINNING':'يدور','HEATING':'يسخن','SOUNDING':'يصدر صوتاً','CONDUCTING':'موصل','MEASURING':'يقيس','CONVERTING':'يحوّل','DRIVE ACTIVE':'المشغل نشط','SENSING':'يستشعر','POWERED':'مزوّد بالطاقة','POWERED • CLOSED':'مزود بالطاقة • مغلق','COIL ENERGIZED':'الملف ممغنط','OPEN':'مفتوح','CLOSED':'مغلق','TRIPPED':'مفصول بالحماية','SOURCE READY':'المصدر جاهز','SHORT CIRCUIT':'قصر كهربائي','Circuit energized':'الدائرة تحت الجهد','Ready':'جاهز','No source':'لا يوجد مصدر','Open circuit':'دائرة مفتوحة','Short circuit':'قصر كهربائي','SOURCE OFF':'المصدر متوقف','POWER PRESENT':'الجهد موجود','STOPPED':'متوقف','WORKING':'يعمل','COIL OFF':'الملف غير ممغنط','BIASED':'منحاز كهربائياً','ENERGIZED':'تحت الجهد','LIVE':'تحت الجهد','OUTPUT ACTIVE':'الخرج نشط','PROCESSING':'يعالج','SENSING • ACTIVE':'استشعار • نشط','No power source':'لا يوجد مصدر طاقة','Source present • circuit open':'المصدر موجود • الدائرة مفتوحة','Open circuit / no current':'دائرة مفتوحة / لا يوجد تيار','Protection tripped':'تم فصل الحماية'
}

export const FIELD_AR = {
  'Source voltage':'جهد المصدر','Internal resistance':'المقاومة الداخلية','Rated voltage':'الجهد الاسمي','Rated power':'القدرة الاسمية','Resistance':'المقاومة','Frequency':'التردد','Current rating':'التيار الاسمي','Trip current':'تيار الفصل','Coil voltage':'جهد الملف','Coil resistance':'مقاومة الملف','Primary voltage':'الجهد الابتدائي','Secondary voltage':'الجهد الثانوي','Efficiency':'الكفاءة','Power rating':'القدرة الاسمية','Sensor active':'الحساس نشط','Input voltage':'جهد الدخل','Output voltage':'جهد الخرج','Threshold':'عتبة التشغيل','Capacitance':'السعة','Inductance':'المحاثة','RMS voltage':'جهد RMS','Line voltage':'جهد الخط','Rated output power':'قدرة الخرج الاسمية','Measurement range':'نطاق القياس','Supply voltage':'جهد التغذية','Output / logic active':'الخرج / المنطق نشط','Primary / input voltage':'جهد الابتدائي / الدخل','Secondary / output voltage':'جهد الثانوي / الخرج','Output frequency':'تردد الخرج','Control threshold':'عتبة التحكم','Zener voltage':'جهد زينر','Forward voltage':'جهد التوصيل الأمامي','Rated / trip current':'التيار الاسمي / تيار الفصل','Rated line current':'تيار الخط الاسمي','Residual trip':'تيار الفصل التفاضلي','Connection resistance':'مقاومة التوصيل','Positive rail voltage':'جهد السكة الموجبة','Negative rail voltage':'جهد السكة السالبة','Clamp voltage':'جهد التثبيت','Monitor voltage':'جهد المراقبة','Undervoltage threshold':'عتبة انخفاض الجهد','Overvoltage threshold':'عتبة زيادة الجهد','Monitor line voltage':'جهد الخط المراقب','Minimum line voltage':'أدنى جهد خط','Primary current':'التيار الابتدائي','Secondary current':'التيار الثانوي','Input forward voltage':'جهد الدخل الأمامي','Optical input active':'الدخل الضوئي نشط','Contact resistance':'مقاومة التلامس'
}

export const STARTER_AR = {
  'Lamp & switch':['مصباح ومفتاح','مصدر تيار مستمر ومفتاح ومصباح'],
  'DOL motor starter':['بادئ تشغيل مباشر DOL','بادئ محرك ثلاثي الطور مع قاطع وكونتاكتور وحماية حرارية'],
  '24 V control circuit':['دائرة تحكم 24 فولت','مزود طاقة وأزرار ضغط ومرحّل ومصباح بيان'],
  'Residential light circuit':['دائرة إنارة منزلية','مصدر AC وقاطع ومفتاح حائط ومصباح LED'],
  'Sensor to PLC':['حساس إلى PLC','مزود 24V وحساس تقاربي ودخل PLC وخرج بيان'],
  'Bridge rectifier test':['اختبار مقوم جسر','محول ومقوم جسر ومكثف وحمل تيار مستمر']
}

export function tr(text, lang='en') { return lang==='ar' ? (UI_AR[text] || text) : text }
export function categoryName(name, lang='en') { return lang==='ar' ? (CATEGORY_AR[name] || name) : name }
export function partName(part, lang='en') { return lang==='ar' ? (PART_AR[part.id] || part.name) : part.name }
export function stateName(text, lang='en') { return lang==='ar' ? (STATE_AR[text] || text) : text }
export function fieldName(text, lang='en') { return lang==='ar' ? (FIELD_AR[text] || text) : text }
export function starterText(template, lang='en') { const a=STARTER_AR[template.title]; return lang==='ar'&&a ? {title:a[0],desc:a[1]} : {title:template.title,desc:template.desc} }
